# Generated by Django 4.2.2 on 2023-06-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_id',
            new_name='productid',
        ),
    ]
