# Generated by Django 4.2.2 on 2023-06-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item_price',
            field=models.IntegerField(),
        ),
    ]
