# Generated by Django 4.2.2 on 2023-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_shopitem_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
